name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Maven package and test
      run: |
        cd /scr/ProjectJava/
        mvn -B package test

    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: 'Test Report'
        path: 'target/surefire-reports/TEST*.xml'
        reporter: 'java-junit'
        fail-on-error: 'true'
        fail-on-empty: 'true'
